version: "3.9"
networks:
  vtodo-dev:
    driver: bridge
services:
  app:
    container_name: web-app
    build:
      context: .
      dockerfile: ./Vtodo.Web/Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres_db
    networks:
      - vtodo-dev
    volumes:
      - ./Builds/appdata/:/VtodoData/
  postgres_db:
    container_name: vtodo_postgres
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: vtodo
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: vtodo
    ports:
      - "5432:5432"
    networks:
      - vtodo-dev
    volumes: 
      - vtodo_postgres-data:/var/lib/postgresql/data
volumes:
  vtodo_postgres-data:
    name: vtodo_postgres-data
