version: "3.9"
networks:
  vtodo-dev:
    driver: bridge
  vtodo-logger-dev:
    driver: bridge
services:
  app:
    container_name: web-app
    build:
      context: .
      dockerfile: ./MainApp/Vtodo.Web/Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres_db
    networks:
      - vtodo-dev
      - vtodo-logger-dev
    volumes:
      - ./MainApp/Builds/appdata/:/VtodoData/
  postgres_db:
    container_name: vtodo_postgres
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: vtodo
      POSTGRES_PASSWORD: dsfsdfsdfDFSFSDFsf234123
      POSTGRES_DB: vtodo
    ports:
      - "5432:5432"
    networks:
      - vtodo-dev
    volumes: 
      - vtodo_postgres-data:/var/lib/postgresql/data
  vtodo_logger_postgres_db:
    container_name: vtodo_logger_postgres
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: vtodo_logger
      POSTGRES_PASSWORD: dsfsdfsddsfsdfsdfkosdlgjsdfDFSFSDFsf234123
      POSTGRES_DB: vtodo_logger
    ports:
      - "5434:5434"
    networks:
      - vtodo-logger-dev
    volumes:
      - vtodo_logger_postgres_data:/var/lib/postgresql/data
  rabbitmq_vtodo_logger:
    image: rabbitmq:3.13.4-management
    hostname: rabbitmq_vtodo_logger
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=vtodo_logger_rabbit
      - RABBITMQ_DEFAULT_PASS=sdfgfsdjhsytjyurjyrxjhnrjsyj
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    networks:
      - vtodo-logger-dev
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./LoggerService/Builds/rabbitmq_vtodo_logger:/var/lib/rabbitmq
volumes:
  vtodo_postgres-data:
    name: vtodo_postgres-data
  vtodo_logger_postgres_data:
    name: vtodo_logger_postgres_data
